%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/srivasp/Documents/Work/Crick_2015/Spindle_orientation/Exp_n_model/Dynamic_shape/Exp_data_rounding/rounding_cells_bipolar_spindles_dna_data.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/25 15:26:29

%% Import the data
[~, ~, raw] = xlsread('rounding_cells_bipolar_spindles_dna_data.xlsx','Sheet1');
raw = raw(4:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,2,3]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Dynamic_shape_all = table;

%% Allocate imported array to column variable names
Dynamic_shape_all.cell_id = data(:,1);
Dynamic_shape_all.frame = data(:,2);
Dynamic_shape_all.time = data(:,3);
Dynamic_shape_all.dna_area = data(:,4);
Dynamic_shape_all.dna_x = data(:,5);
Dynamic_shape_all.dna_y = data(:,6);
Dynamic_shape_all.dna_length = data(:,7);
Dynamic_shape_all.dna_width = data(:,8);
Dynamic_shape_all.dna_angle = data(:,9);
Dynamic_shape_all.cell_area = data(:,10);
Dynamic_shape_all.cell_x = data(:,11);
Dynamic_shape_all.cell_y = data(:,12);
Dynamic_shape_all.cell_length = data(:,13);
Dynamic_shape_all.cell_width = data(:,14);
Dynamic_shape_all.cell_angle = data(:,15);

%% Clear temporary variables
clearvars data raw stringVectors R;













