%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/srivasp/Documents/Work/Crick_2015/Spindle_orientation/Final_all_parts_Git/Dynamic_shape/Exp_data_rounding/time_angles.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/13 15:47:22

%% Import the data
[~, ~, raw] = xlsread('/Users/srivasp/Documents/Work/Crick_2015/Spindle_orientation/Final_all_parts_Git/Dynamic_shape/Exp_data_rounding/time_angles.xlsx','Sheet1');
raw = raw(2:end,1:5);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
timeangles = table;

%% Allocate imported array to column variable names
timeangles.angles_30min = data(:,1);
timeangles.angles_anaphase = data(:,2);
timeangles.angles_9min = data(:,3);
timeangles.cell_id = data(:,4);
timeangles.initial_ar = data(:,5);

%% Clear temporary variables
clearvars data raw R;