%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/srivasp/Documents/Work/Crick_2015/Spindle_orientation/Exp_n_model/Static_shape/Centered_nucleus/Static_shape_develop/Sys_params.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/02/06 12:16:24

%% Import the data
[~, ~, raw] = xlsread('Monopole_params.xlsx','Sheet1');
raw = raw(end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
params = table;

%% Allocate imported array to column variable names
params.dna_half_length = data(:,1);
params.inhibition = data(:,2);
params.astral_Mts = data(:,3);
params.spindle_half_length = data(:,4);
params.Diffusion = data(:,5);
params.mobility = data(:,6);
params.kon_far = data(:,7);
params.kon_near = data(:,8);
params.koff_far = data(:,9);
params.koff_near = data(:,10);

%% Clear temporary variables
clearvars data raw;