%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/srivasp/Documents/Work/Crick_2015/Spindle_orientation/Final_all_parts_Git/Updated_codes_functions/Dynamic_shape/Exp_analyses/LGN_analysis_7Cells/analysis.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/06 16:16:39

%% Import the data
[~, ~, raw] = xlsread('analysis.xlsx','Sheet1');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[2,4]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(2:end,[1,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
analysis = table;

%% Allocate imported array to column variable names
analysis.VarName1 = data(:,1);
analysis.file = categorical(stringVectors(:,1));
analysis.cell_id = data(:,2);
analysis.condition = categorical(stringVectors(:,2));
analysis.area = data(:,3);
analysis.lgn_mean = data(:,4);
analysis.length = data(:,5);
analysis.major = data(:,6);
analysis.minor = data(:,7);
analysis.angle = data(:,8);
analysis.z = data(:,9);
analysis.frame = data(:,10);
analysis.s = data(:,11);
analysis.lgn_intensity = data(:,12);
analysis.lgn_background = data(:,13);
analysis.cell_ar = data(:,14);
analysis.initial_cell_angle = data(:,15);
analysis.time = data(:,16);
analysis.degrees = data(:,17);
analysis.s_norm = data(:,18);
analysis.lgn_norm = data(:,19);
analysis.x_a = data(:,20);
analysis.y_a = data(:,21);
analysis.z_a = data(:,22);
analysis.x_b = data(:,23);
analysis.y_b = data(:,24);
analysis.z_b = data(:,25);
analysis.z_res = data(:,26);
analysis.spindle_length = data(:,27);
analysis.theta_raw = data(:,28);
analysis.phi = data(:,29);
analysis.theta = data(:,30);

%% Clear temporary variables
clearvars data raw stringVectors R;